/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#091426",
        "primary-container": "#1e293b",
        "on-primary": "#ffffff",
        "on-primary-container": "#8590a6",
        "secondary": "#006591",
        "secondary-container": "#39b8fd",
        "secondary-fixed": "#c9e6ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#004666",
        "tertiary": "#001815",
        "tertiary-container": "#002f29",
        "tertiary-fixed": "#71f8e4",
        "tertiary-fixed-dim": "#4fdbc8",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#00a292",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#45474c",
        "outline": "#75777d",
        "outline-variant": "#c5c6cd",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      }
    },
  },
  plugins: [],
}
